---
- name: Install prerequisite computate_sqlite
  tags:
    - prerequisite
    - prerequisite_sqlite
  include_role:
    name: computate.computate_sqlite
- name: Install prerequisite computate_fox
  tags:
    - prerequisite
    - prerequisite_fox
  include_role:
    name: computate.computate_fox
- name: "Install dependencies as root: {{ APP_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ APP_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
- name: "Install dependencies as user {{ APP_USER }}: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
  when: INSTALL_DEPENDENCIES.failed
- name: "Create the directory {{ APP_SRC }}"
  file:
    name: "{{ APP_SRC }}"
    owner: "{{ APP_USER }}"
    state: directory
  become: "{{ APP_ROOT }}"
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO_SSH }} source code into {{ APP_SRC }}"
  ansible.builtin.git:
    repo: "{{ APP_REPO_SSH }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  ignore_errors: true
  when: not APP_README_PATH.stat.exists
  register: CLONE_REPO
- name: "Clone the {{ APP_REPO_HTTPS }} source code into {{ APP_SRC }}"
  ansible.builtin.git:
    repo: "{{ APP_REPO_HTTPS }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists and CLONE_REPO.failed
- name: "Create the directory {{ APP_SRC }}/build/cmake-build"
  file:
    name: "{{ APP_SRC }}/build/cmake-build"
    owner: "{{ APP_USER }}"
    state: directory
  become: "{{ APP_ROOT }}"
- name: "Run the cmake script in {{ APP_SRC }}/build/cmake-build: cmake -DCMAKE_INSTALL_PREFIX={{ APP_PREFIX }} ../.."
  shell:
    cmd: "cmake -DCMAKE_INSTALL_PREFIX={{ APP_PREFIX }} ../.."
    chdir: "{{ APP_SRC }}/build/cmake-build"
- name: "Run the make script in {{ APP_SRC }}"
  shell:
    cmd: "env PKG_CONFIG_PATH={{ APP_PREFIX }}/lib/pkgconfig LD_LIBRARY_PATH={{ APP_PREFIX }}/lib make -j {{ MAKE_CORES }}"
    chdir: "{{ APP_SRC }}/build/cmake-build"
- name: "Run the make install script in {{ APP_SRC }}"
  shell:
    cmd: "env PKG_CONFIG_PATH={{ APP_PREFIX }}/lib/pkgconfig LD_LIBRARY_PATH={{ APP_PREFIX }}/lib make install"
    chdir: "{{ APP_SRC }}/build/cmake-build"
  become: "{{ APP_ROOT }}"
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"
    mode: 0775
  become: "{{ APP_ROOT }}"

